name: rawg_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.9
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  retrofit: ^1.3.4
  json_serializable: ^3.5.0
  cached_network_image: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.8+2
  build_runner: any

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
